version: "3.8"

services:
    mongo1:
        image: mongo:5
        container_name: mongo1
        command: ["--replSet", "rs01", "--bind_ip_all", "--port", "30001"]
        volumes:
            - ./data/mongo-1:/data/db
        ports:
            - 30001:30001

    mongo2:
        image: mongo:5
        container_name: mongo2
        command: ["--replSet", "rs01", "--bind_ip_all", "--port", "30002"]
        volumes:
            - ./data/mongo-2:/data/db
        ports:
            - 30002:30002

    mongo3:
        image: mongo:5
        container_name: mongo3
        command: ["--replSet", "rs01", "--bind_ip_all", "--port", "30003"]
        volumes:
            - ./data/mongo-3:/data/db
        ports:
            - 30003:30003